language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 5.6
      env: deps=low
    - php: 5.6
      env: deps=high
    - php: hhvm
    - php: nightly
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true

install:
  - composer self-update -q
  - if [ -z "$deps" ]; then composer install -n; fi;
  - if [ "$deps" = "low" ]; then composer update --prefer-lowest --prefer-stable --prefer-source -n; fi;
  - if [ "$deps" = "high" ]; then composer update --prefer-source -n; fi;

script: vendor/bin/phpunit -v --coverage-clover=coverage.clover

after_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;'

notifications:
  webhooks:
    urls: ['https://webhooks.gitter.im/e/9ccc2378e6c0de6480f8']
    on_success: change
    on_failure: always
    on_start:   never
